---

# Forked from Netcracker/.github workflow-templates/check-license.yaml.
# Checks the licenses of the Go modules in the repository via the shared
# go-check-license reusable workflow. It needs a .wwhrd.yml allowlist in the
# repository root. Example:
# https://github.com/netcracker/qubership-workflow-hub/blob/main/docs/examples/.wwhrd.yml
# Fails if any module has a disallowed or missing license.

name: Check Go Modules Licenses
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: check-license-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check-license:
    name: "Check Go Modules Licenses"
    uses: netcracker/qubership-workflow-hub/.github/workflows/go-check-license.yaml@cabbb90e9471163cfac84bd50ff0296b2803b44c # v2.3.0
